name: Publish Release

on:
  release:
      types: [published]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  CONFIGURATION: "Release"
  VERBOSITY:  "Minimal" 
  
jobs:
  Release:
    name: Release TinyCLR
    runs-on: [windows-latest]
    strategy:
      matrix:
        dotnet: ['3.1.100']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract build information into variables
      id: info
      run: |
        echo "##[set-output name=version;]$(echo $env:GITHUB_REF.Replace('refs/tags/v',''))"
        echo "##[set-output name=build;]$(echo prebuild.$(git rev-list --count HEAD))"
        echo "##[set-output name=copyright;]$(echo © $(date -u +%Y) Bytewizer.  All rights reserved.)"    
    
    - name: Show build information
      run: |
        echo version=${{ steps.info.outputs.version }}
        echo build=${{ steps.info.outputs.build }}
        echo copyright=${{ steps.info.outputs.copyright }}
    
    - name: Setup build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Display dotnet information
      run: dotnet --info

    - name: Restore packages
      run: dotnet restore --verbosity ${env:VERBOSITY}
 
    - name: Build libraries
      run: >-
        dotnet build -p:BuildNumber= "${{ steps.info.outputs.build }}" -p:Version="${{ steps.info.outputs.version }}" 
        --no-restore
        --verbosity ${env:VERBOSITY}
        --configuration ${env:CONFIGURATION} 
        
    - name: Pack libraries
      run: >- 
        dotnet pack -p:BuildNumber= "${{ steps.info.outputs.build }}" -p:PackageVersion="${{ steps.info.outputs.version }}" -p:Copyright="${{ steps.info.outputs.copyright }}"
        --include-symbols 
        --no-restore 
        --no-build 
        --verbosity ${env:VERBOSITY} 
        --configuration ${env:CONFIGURATION} 
        --output .builds/artifacts

    - name: Upload release artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Release
        path: .builds/artifacts
    
    - name: Create release asset
      run: Compress-Archive -DestinationPath .builds/packages.zip -Path .builds/artifacts/*.*nupkg

    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .builds/packages.zip
        asset_name: Packages.zip
        asset_content_type: application/zip
    
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: 'latest' 

#  - name: Publish package to github
#    run: |
#    nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/microcompiler/index.json" -UserName microcompiler -Password ${{secrets.GITHUB_TOKEN}}
#    nuget push artifacts/*.nupkg -Source "GitHub"

#    - name: Publish package to nuget
#      run: |
#        nuget sources Add -Name "NuGet" -Source "https://int.nugettest.org"
#        nuget push artifacts/*.*nupkg -Source "NuGet"
